# Generated by Django 3.0.7 on 2020-06-25 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_name', models.CharField(max_length=200)),
                ('event_info', models.TextField()),
                ('event_poster', models.ImageField(blank=True, upload_to='static/images/')),
                ('event_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_tag', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Sub_Tags',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_type', models.CharField(choices=[('Core Committee', 'Core Committee'), ('Executive Committee', 'Executive Committee')], default='Core Committee', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
                ('designation', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('linkedIn_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDF_description', models.CharField(blank=True, max_length=200)),
                ('PDF', models.FileField(blank=True, upload_to='static/images/')),
                ('Video_description', models.CharField(blank=True, max_length=200)),
                ('Video', models.FileField(blank=True, upload_to='static/images/')),
                ('Reference_Link', models.URLField(blank=True)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('sub_tag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pclub.Sub_Tags')),
                ('tag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pclub.Tags')),
            ],
            options={
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='static/images/')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pclub.Events')),
            ],
        ),
    ]
