# Generated by Django 3.0.6 on 2020-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pclub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_name', models.CharField(max_length=200)),
                ('event_info', models.TextField()),
                ('event_url', models.URLField()),
            ],
        ),
    ]
