# Generated by Django 3.0.6 on 2020-06-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pclub', '0002_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
                ('designation', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('linkedIn_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='event_url',
            field=models.URLField(blank=True),
        ),
    ]
