# Generated by Django 3.0.7 on 2020-06-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pclub', '0003_auto_20200625_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Newsletter',
            },
        ),
        migrations.DeleteModel(
            name='BlogComments',
        ),
    ]
